server:
  port: 8081

spring:
  application:
    name: ledger-svc
  datasource:
    # 環境変数で上書き可能 (ECS Secrets / local .env)
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/app}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:app}
    password: ${SPRING_DATASOURCE_PASSWORD:app}
    hikari:
      # DB が起動前でもアプリ自体は STARTUP させ、readiness で判定するため失敗で落とさない
      initializationFailTimeout: 0
      connectionTimeout: 30000
      maximumPoolSize: 10
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  sql:
    init:
      mode: never
  jackson:
    serialization:
      indent_output: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: "never"

safepocket:
  cognito:
    issuer: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_example
    audience: 111111example
    enabled: ${SAFEPOCKET_USE_COGNITO:false}
  plaid:
    client-id: ${PLAID_CLIENT_ID:demo-client}
    client-secret: ${PLAID_CLIENT_SECRET:demo-secret}
    redirect-uri: https://app.safepocket.local/plaid/callback
  ai:
    model: gpt-5-nano
    endpoint: https://api.openai.com/v1/responses
    api-key: ${OPENAI_API_KEY:}
  security:
    dev-jwt-secret: ${SAFEPOCKET_DEV_JWT_SECRET:dev-secret-key-for-local-development-only}
