server:
  port: 8090

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ${COGNITO_CLIENT_ID:5ge4c1b382ft2v71rvip0rrhqv}
            client-secret: ${COGNITO_CLIENT_SECRET:replace-me}
            scope:
              - openid
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Cognito
        provider:
          cognito:
            issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_mFd4O5tGY
            user-name-attribute: username

logging:
  level:
    org.springframework.security: INFO
